# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orES0ONhRzhyM18JqEtEkp1O2Q_s89h0
"""

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
import numpy as np

print("Chargement des documents...")


pdf_files = ["loi 09-08.pdf", "RGPD.pdf"]

# Chargement des PDFs
all_docs = []
for pdf in pdf_files:
    print(f"Lecture de {pdf}")
    try:
        loader = PyPDFLoader(pdf)
        docs = loader.load()
        all_docs.extend(docs)
    except Exception as e:
        print(f"Erreur avec {pdf}: {e}")

if not all_docs:
    print("Aucun document chargé. Vérifiez que les fichiers PDF sont bien uploadés.")
else:
    print(f"{len(all_docs)} pages chargées au total")

    # Découpage en chunks
    print("Découpage des documents...")
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=800,
        chunk_overlap=150,
        length_function=len,
    )
    chunks = splitter.split_documents(all_docs)
    print(f"{len(chunks)} sections créées")

    # Création des embeddings (100% gratuit, multilingue)
    print("Création des embeddings (peut prendre 1-2 minutes)...")
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        model_kwargs={'device': 'cpu'}
    )

    # Base vectorielle FAISS (gratuit et rapide)
    print("Construction de la base de recherche...")
    vectorstore = FAISS.from_documents(chunks, embeddings)

    print("Système prêt! Aucune clé API nécessaire")
    print("Documents chargés: Loi 09-08 et Guide CNIL RGPD")

# ==== FONCTION DE RECHERCHE (Cellule 3) ====
def rechercher(question, k=5):
    """
    Recherche les passages les plus pertinents pour une question

    Args:
        question: Votre question
        k: Nombre de résultats à retourner
    """
    if 'vectorstore' not in globals():
        print("Veuillez d'abord charger les documents (Cellule 2)")
        return []

    print(f"\nQuestion: {question}\n")
    print("="*70)

    # Recherche par similarité
    results = vectorstore.similarity_search_with_score(question, k=k)

    for i, (doc, score) in enumerate(results, 1):
        print(f"\nRÉSULTAT {i} (Score de pertinence: {score:.3f})")
        source = doc.metadata.get('source', 'inconnu')
        if 'loi 09-08' in source or 'loi0908' in source:
            print(f"Source: Loi 09-08")
        elif 'cnil' in source.lower() or 'rgpd' in source.lower():
            print(f"Source: Guide CNIL RGPD")
        else:
            print(f"Source: {source}")
        print(f"Page: {doc.metadata.get('page', '?')}")
        print(f"\nContenu:")
        print("-" * 70)
        print(doc.page_content)
        print("-" * 70)

    return results

# ==== FONCTION AVEC RÉSUMÉ (Cellule 4) ====
def repondre(question, k=4):
    """
    Répond à une question en trouvant les passages pertinents
    """
    if 'vectorstore' not in globals():
        print("Veuillez d'abord charger les documents (Cellule 2)")
        return []

    print(f"\nQuestion: {question}\n")

    # Recherche des passages pertinents
    results = vectorstore.similarity_search(question, k=k)

    print("INFORMATIONS TROUVÉES DANS VOS DOCUMENTS:")
    print("="*70)

    for i, doc in enumerate(results, 1):
        source = doc.metadata.get('source', '')
        if 'loi 09-08' in source or 'loi0908' in source:
            doc_name = "Loi 09-08"
        elif 'cnil' in source.lower() or 'rgpd' in source.lower():
            doc_name = "Guide CNIL"
        else:
            doc_name = "Document"

        print(f"\n[{i}] {doc_name} - Page {doc.metadata.get('page', '?')}")
        content = doc.page_content[:400] + "..." if len(doc.page_content) > 400 else doc.page_content
        print(content)
        print()

    print("="*70)
    print("Ces extraits contiennent les informations pertinentes de vos documents.")

    return results

# ==== RECHERCHE PAR MOTS-CLÉS (Cellule 5) ====
def recherche_mots_cles(*mots_cles, k=3):
    """
    Recherche par mots-clés multiples

    Exemple: recherche_mots_cles("données personnelles", "protection")
    """
    if 'vectorstore' not in globals():
        print("Veuillez d'abord charger les documents (Cellule 2)")
        return []

    query = " ".join(mots_cles)
    print(f"Recherche: {query}\n")

    results = vectorstore.similarity_search(query, k=k)

    for i, doc in enumerate(results, 1):
        source = doc.metadata.get('source', '')
        if 'loi 09-08' in source or 'loi0908' in source:
            doc_name = "Loi 09-08"
        elif 'cnil' in source.lower() or 'rgpd' in source.lower():
            doc_name = "Guide CNIL"
        else:
            doc_name = "Document"

        print(f"\nEXTRAIT {i} - {doc_name}")
        print(f"Page: {doc.metadata.get('page', '?')}")
        print("-" * 70)
        print(doc.page_content)
        print("-" * 70)

    return results

# ==== EXEMPLES D'UTILISATION (Cellule 6) ====
if 'vectorstore' in globals():
    print("\n" + "="*70)
    print("EXEMPLES DE RECHERCHE")
    print("="*70)

    # Exemple 1: Questions sur la loi 09-08
    print("\n### Question 1: À propos de la loi 09-08 ###")
    repondre("Quelles sont les obligations concernant les données personnelles selon la loi 09-08 ?", k=3)

    print("\n\n### Question 2: À propos du RGPD ###")
    repondre("Comment sécuriser les mots de passe selon le RGPD ?", k=3)

    print("\n\n### Question 3: Recherche par mots-clés ###")
    recherche_mots_cles("consentement", "personne concernée", k=3)
else:
    print("Les documents n'ont pas été chargés. Exécutez d'abord la Cellule 2.")

# ==== MODE INTERACTIF (Cellule 7) ====
if 'vectorstore' in globals():
    print("\n" + "="*70)
    print("MODE INTERACTIF")
    print("="*70)
    print("Commandes:")
    print("  - Tapez votre question normalement")
    print("  - 'quit' ou 'q' pour quitter")
    print("  - 'help' pour l'aide")
    print("="*70 + "\n")


# ==== QUESTIONS PRÉDÉFINIES (Alternative - Cellule 8) ====
if 'vectorstore' in globals():
    questions_exemples = [
        "Qu'est-ce qu'une donnée à caractère personnel selon la loi 09-08 ?",
        "Quels sont les droits de la personne concernée ?",
        "Comment gérer le consentement des utilisateurs ?",
        "Quelles sont les sanctions en cas de non-respect ?",
        "Comment authentifier les utilisateurs de manière sécurisée ?",
        "Quelles mesures de sécurité pour protéger les données ?",
        "Qu'est-ce que la Commission nationale de contrôle ?",
        "Comment sauvegarder les données personnelles ?",
    ]